const allTags = [
        "python",
        "javascript",
        "discord",
        "java",
        "rust",
        "c",
        "cpp",
        "csharp",
        "nodejs",
        "html",
        "css",
        "go",
        "mongodb",
        "graphql",
        "ruby",
        "php",
        "git-and-github",
        "bash",
        "npm",
        "nix",
        "swift",
        "misc",
        "domains",
        "kaboom",
        "game-dev",
        "react",
        "kotlin",
        "lua",
        "haskell",
        "sql",
        "typescript",
        "r",
        "basic",
        "dart",
        "elixir",
        "svelte",
        "scala",
        "crystal",
      ].sort((a,b) => a.localeCompare(b)); 
export default allTags;

